import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const prod = process.argv[2] === "production";
const vaultPluginDir = process.env.VAULT_PLUGIN_DIR;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const copyToVaultPlugin = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd(() => {
      if (!vaultPluginDir) return;
      if (!fs.existsSync(vaultPluginDir)) {
        fs.mkdirSync(vaultPluginDir, { recursive: true });
      }
      for (const f of ["main.js", "manifest.json", "styles.css"]) {
        if (fs.existsSync(f)) {
          fs.copyFileSync(f, path.join(vaultPluginDir, f));
        }
      }
      console.log(`[copy-to-vault] synced to ${vaultPluginDir}`);
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [copyToVaultPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
